# ~/nix-btw/hardware/default.nix
{ config, lib, pkgs, ... }:

{
  imports = [
    # Pull in the autogenerated hardware scan
    ./hardware-configuration.nix
    ./nvidia-graphics.nix
  ];

  # Bootloader configurations
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
}
